//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlaggen {
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute( "System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0" )]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        /// <summary>
        /// Defines the resourceMan
        /// </summary>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        /// Defines the resourceCulture
        /// </summary>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Initializes a new instance of the <see cref="Resources"/> class.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute( "Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode" )]
        internal Resources() {
        }

        /// <summary>
        /// Gets the ResourceManager
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute( global::System.ComponentModel.EditorBrowsableState.Advanced )]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if ( object.ReferenceEquals( resourceMan, null ) ) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Opdracht2.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Gets or sets the Culture
        /// Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute( global::System.ComponentModel.EditorBrowsableState.Advanced )]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Gets the _0
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0 {
            get {
                object obj = ResourceManager.GetObject("_0", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _1
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _10
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10 {
            get {
                object obj = ResourceManager.GetObject("_10", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _100
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _100 {
            get {
                object obj = ResourceManager.GetObject("_100", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _101
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _101 {
            get {
                object obj = ResourceManager.GetObject("_101", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _102
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _102 {
            get {
                object obj = ResourceManager.GetObject("_102", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _103
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _103 {
            get {
                object obj = ResourceManager.GetObject("_103", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _104
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _104 {
            get {
                object obj = ResourceManager.GetObject("_104", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _105
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _105 {
            get {
                object obj = ResourceManager.GetObject("_105", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _106
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _106 {
            get {
                object obj = ResourceManager.GetObject("_106", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _107
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _107 {
            get {
                object obj = ResourceManager.GetObject("_107", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _108
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _108 {
            get {
                object obj = ResourceManager.GetObject("_108", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _109
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _109 {
            get {
                object obj = ResourceManager.GetObject("_109", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _11
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("_11", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _110
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _110 {
            get {
                object obj = ResourceManager.GetObject("_110", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _111
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _111 {
            get {
                object obj = ResourceManager.GetObject("_111", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _112
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _112 {
            get {
                object obj = ResourceManager.GetObject("_112", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _113
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _113 {
            get {
                object obj = ResourceManager.GetObject("_113", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _114
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _114 {
            get {
                object obj = ResourceManager.GetObject("_114", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _115
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _115 {
            get {
                object obj = ResourceManager.GetObject("_115", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _116
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _116 {
            get {
                object obj = ResourceManager.GetObject("_116", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _117
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _117 {
            get {
                object obj = ResourceManager.GetObject("_117", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _118
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _118 {
            get {
                object obj = ResourceManager.GetObject("_118", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _119
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _119 {
            get {
                object obj = ResourceManager.GetObject("_119", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _12
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12 {
            get {
                object obj = ResourceManager.GetObject("_12", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _120
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _120 {
            get {
                object obj = ResourceManager.GetObject("_120", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _121
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _121 {
            get {
                object obj = ResourceManager.GetObject("_121", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _122
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _122 {
            get {
                object obj = ResourceManager.GetObject("_122", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _123
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _123 {
            get {
                object obj = ResourceManager.GetObject("_123", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _124
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _124 {
            get {
                object obj = ResourceManager.GetObject("_124", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _125
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _125 {
            get {
                object obj = ResourceManager.GetObject("_125", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _126
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _126 {
            get {
                object obj = ResourceManager.GetObject("_126", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _127
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _127 {
            get {
                object obj = ResourceManager.GetObject("_127", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _128
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _128 {
            get {
                object obj = ResourceManager.GetObject("_128", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _129
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _129 {
            get {
                object obj = ResourceManager.GetObject("_129", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _13
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _13 {
            get {
                object obj = ResourceManager.GetObject("_13", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _130
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _130 {
            get {
                object obj = ResourceManager.GetObject("_130", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _131
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _131 {
            get {
                object obj = ResourceManager.GetObject("_131", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _132
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _132 {
            get {
                object obj = ResourceManager.GetObject("_132", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _133
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _133 {
            get {
                object obj = ResourceManager.GetObject("_133", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _134
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _134 {
            get {
                object obj = ResourceManager.GetObject("_134", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _135
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _135 {
            get {
                object obj = ResourceManager.GetObject("_135", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _136
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _136 {
            get {
                object obj = ResourceManager.GetObject("_136", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _137
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _137 {
            get {
                object obj = ResourceManager.GetObject("_137", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _138
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _138 {
            get {
                object obj = ResourceManager.GetObject("_138", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _139
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _139 {
            get {
                object obj = ResourceManager.GetObject("_139", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _14
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _14 {
            get {
                object obj = ResourceManager.GetObject("_14", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _140
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _140 {
            get {
                object obj = ResourceManager.GetObject("_140", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _141
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _141 {
            get {
                object obj = ResourceManager.GetObject("_141", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _142
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _142 {
            get {
                object obj = ResourceManager.GetObject("_142", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _143
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _143 {
            get {
                object obj = ResourceManager.GetObject("_143", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _144
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _144 {
            get {
                object obj = ResourceManager.GetObject("_144", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _145
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _145 {
            get {
                object obj = ResourceManager.GetObject("_145", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _146
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _146 {
            get {
                object obj = ResourceManager.GetObject("_146", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _147
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _147 {
            get {
                object obj = ResourceManager.GetObject("_147", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _148
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _148 {
            get {
                object obj = ResourceManager.GetObject("_148", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _149
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _149 {
            get {
                object obj = ResourceManager.GetObject("_149", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _15
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _15 {
            get {
                object obj = ResourceManager.GetObject("_15", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _150
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _150 {
            get {
                object obj = ResourceManager.GetObject("_150", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _151
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _151 {
            get {
                object obj = ResourceManager.GetObject("_151", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _152
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _152 {
            get {
                object obj = ResourceManager.GetObject("_152", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _153
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _153 {
            get {
                object obj = ResourceManager.GetObject("_153", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _154
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _154 {
            get {
                object obj = ResourceManager.GetObject("_154", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _155
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _155 {
            get {
                object obj = ResourceManager.GetObject("_155", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _156
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _156 {
            get {
                object obj = ResourceManager.GetObject("_156", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _157
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _157 {
            get {
                object obj = ResourceManager.GetObject("_157", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _158
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _158 {
            get {
                object obj = ResourceManager.GetObject("_158", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _159
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _159 {
            get {
                object obj = ResourceManager.GetObject("_159", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _16
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _16 {
            get {
                object obj = ResourceManager.GetObject("_16", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _160
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _160 {
            get {
                object obj = ResourceManager.GetObject("_160", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _161
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _161 {
            get {
                object obj = ResourceManager.GetObject("_161", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _162
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _162 {
            get {
                object obj = ResourceManager.GetObject("_162", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _163
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _163 {
            get {
                object obj = ResourceManager.GetObject("_163", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _164
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _164 {
            get {
                object obj = ResourceManager.GetObject("_164", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _165
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _165 {
            get {
                object obj = ResourceManager.GetObject("_165", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _166
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _166 {
            get {
                object obj = ResourceManager.GetObject("_166", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _167
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _167 {
            get {
                object obj = ResourceManager.GetObject("_167", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _168
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _168 {
            get {
                object obj = ResourceManager.GetObject("_168", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _169
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _169 {
            get {
                object obj = ResourceManager.GetObject("_169", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _17
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _17 {
            get {
                object obj = ResourceManager.GetObject("_17", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _170
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _170 {
            get {
                object obj = ResourceManager.GetObject("_170", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _171
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _171 {
            get {
                object obj = ResourceManager.GetObject("_171", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _172
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _172 {
            get {
                object obj = ResourceManager.GetObject("_172", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _173
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _173 {
            get {
                object obj = ResourceManager.GetObject("_173", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _174
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _174 {
            get {
                object obj = ResourceManager.GetObject("_174", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _175
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _175 {
            get {
                object obj = ResourceManager.GetObject("_175", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _176
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _176 {
            get {
                object obj = ResourceManager.GetObject("_176", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _177
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _177 {
            get {
                object obj = ResourceManager.GetObject("_177", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _178
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _178 {
            get {
                object obj = ResourceManager.GetObject("_178", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _179
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _179 {
            get {
                object obj = ResourceManager.GetObject("_179", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _18
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _18 {
            get {
                object obj = ResourceManager.GetObject("_18", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _180
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _180 {
            get {
                object obj = ResourceManager.GetObject("_180", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _181
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _181 {
            get {
                object obj = ResourceManager.GetObject("_181", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _182
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _182 {
            get {
                object obj = ResourceManager.GetObject("_182", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _183
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _183 {
            get {
                object obj = ResourceManager.GetObject("_183", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _184
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _184 {
            get {
                object obj = ResourceManager.GetObject("_184", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _185
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _185 {
            get {
                object obj = ResourceManager.GetObject("_185", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _186
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _186 {
            get {
                object obj = ResourceManager.GetObject("_186", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _187
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _187 {
            get {
                object obj = ResourceManager.GetObject("_187", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _188
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _188 {
            get {
                object obj = ResourceManager.GetObject("_188", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _189
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _189 {
            get {
                object obj = ResourceManager.GetObject("_189", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _19
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _19 {
            get {
                object obj = ResourceManager.GetObject("_19", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _190
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _190 {
            get {
                object obj = ResourceManager.GetObject("_190", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _191
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _191 {
            get {
                object obj = ResourceManager.GetObject("_191", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _192
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _192 {
            get {
                object obj = ResourceManager.GetObject("_192", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _193
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _193 {
            get {
                object obj = ResourceManager.GetObject("_193", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _194
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _194 {
            get {
                object obj = ResourceManager.GetObject("_194", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _2
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _20
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _20 {
            get {
                object obj = ResourceManager.GetObject("_20", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _21
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _21 {
            get {
                object obj = ResourceManager.GetObject("_21", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _22
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _22 {
            get {
                object obj = ResourceManager.GetObject("_22", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _23
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _23 {
            get {
                object obj = ResourceManager.GetObject("_23", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _24
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _24 {
            get {
                object obj = ResourceManager.GetObject("_24", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _25
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _25 {
            get {
                object obj = ResourceManager.GetObject("_25", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _26
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _26 {
            get {
                object obj = ResourceManager.GetObject("_26", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _27
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _27 {
            get {
                object obj = ResourceManager.GetObject("_27", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _28
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _28 {
            get {
                object obj = ResourceManager.GetObject("_28", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _29
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _29 {
            get {
                object obj = ResourceManager.GetObject("_29", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _3
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _30
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _30 {
            get {
                object obj = ResourceManager.GetObject("_30", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _31
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _31 {
            get {
                object obj = ResourceManager.GetObject("_31", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _32
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32 {
            get {
                object obj = ResourceManager.GetObject("_32", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _33
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _33 {
            get {
                object obj = ResourceManager.GetObject("_33", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _34
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _34 {
            get {
                object obj = ResourceManager.GetObject("_34", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _35
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _35 {
            get {
                object obj = ResourceManager.GetObject("_35", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _36
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _36 {
            get {
                object obj = ResourceManager.GetObject("_36", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _37
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _37 {
            get {
                object obj = ResourceManager.GetObject("_37", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _38
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _38 {
            get {
                object obj = ResourceManager.GetObject("_38", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _39
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _39 {
            get {
                object obj = ResourceManager.GetObject("_39", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _4
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _40
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _40 {
            get {
                object obj = ResourceManager.GetObject("_40", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _41
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _41 {
            get {
                object obj = ResourceManager.GetObject("_41", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _42
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _42 {
            get {
                object obj = ResourceManager.GetObject("_42", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _43
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _43 {
            get {
                object obj = ResourceManager.GetObject("_43", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _44
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _44 {
            get {
                object obj = ResourceManager.GetObject("_44", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _45
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _45 {
            get {
                object obj = ResourceManager.GetObject("_45", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _46
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _46 {
            get {
                object obj = ResourceManager.GetObject("_46", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _47
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _47 {
            get {
                object obj = ResourceManager.GetObject("_47", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _48
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _48 {
            get {
                object obj = ResourceManager.GetObject("_48", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _49
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _49 {
            get {
                object obj = ResourceManager.GetObject("_49", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _5
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5 {
            get {
                object obj = ResourceManager.GetObject("_5", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _50
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _50 {
            get {
                object obj = ResourceManager.GetObject("_50", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _51
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _51 {
            get {
                object obj = ResourceManager.GetObject("_51", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _52
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _52 {
            get {
                object obj = ResourceManager.GetObject("_52", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _53
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _53 {
            get {
                object obj = ResourceManager.GetObject("_53", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _54
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _54 {
            get {
                object obj = ResourceManager.GetObject("_54", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _55
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _55 {
            get {
                object obj = ResourceManager.GetObject("_55", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _56
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _56 {
            get {
                object obj = ResourceManager.GetObject("_56", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _57
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _57 {
            get {
                object obj = ResourceManager.GetObject("_57", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _58
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _58 {
            get {
                object obj = ResourceManager.GetObject("_58", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _59
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _59 {
            get {
                object obj = ResourceManager.GetObject("_59", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _6
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _60
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _60 {
            get {
                object obj = ResourceManager.GetObject("_60", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _61
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _61 {
            get {
                object obj = ResourceManager.GetObject("_61", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _62
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _62 {
            get {
                object obj = ResourceManager.GetObject("_62", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _63
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _63 {
            get {
                object obj = ResourceManager.GetObject("_63", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _64
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _64 {
            get {
                object obj = ResourceManager.GetObject("_64", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _65
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _65 {
            get {
                object obj = ResourceManager.GetObject("_65", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _66
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _66 {
            get {
                object obj = ResourceManager.GetObject("_66", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _67
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _67 {
            get {
                object obj = ResourceManager.GetObject("_67", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _68
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _68 {
            get {
                object obj = ResourceManager.GetObject("_68", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _69
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _69 {
            get {
                object obj = ResourceManager.GetObject("_69", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _7
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7 {
            get {
                object obj = ResourceManager.GetObject("_7", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _70
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _70 {
            get {
                object obj = ResourceManager.GetObject("_70", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _71
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _71 {
            get {
                object obj = ResourceManager.GetObject("_71", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _72
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _72 {
            get {
                object obj = ResourceManager.GetObject("_72", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _73
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _73 {
            get {
                object obj = ResourceManager.GetObject("_73", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _74
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _74 {
            get {
                object obj = ResourceManager.GetObject("_74", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _75
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _75 {
            get {
                object obj = ResourceManager.GetObject("_75", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _76
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _76 {
            get {
                object obj = ResourceManager.GetObject("_76", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _77
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _77 {
            get {
                object obj = ResourceManager.GetObject("_77", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _78
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _78 {
            get {
                object obj = ResourceManager.GetObject("_78", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _79
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _79 {
            get {
                object obj = ResourceManager.GetObject("_79", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _8
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8 {
            get {
                object obj = ResourceManager.GetObject("_8", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _80
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _80 {
            get {
                object obj = ResourceManager.GetObject("_80", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _81
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _81 {
            get {
                object obj = ResourceManager.GetObject("_81", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _82
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _82 {
            get {
                object obj = ResourceManager.GetObject("_82", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _83
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _83 {
            get {
                object obj = ResourceManager.GetObject("_83", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _84
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _84 {
            get {
                object obj = ResourceManager.GetObject("_84", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _85
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _85 {
            get {
                object obj = ResourceManager.GetObject("_85", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _86
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _86 {
            get {
                object obj = ResourceManager.GetObject("_86", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _87
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _87 {
            get {
                object obj = ResourceManager.GetObject("_87", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _88
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _88 {
            get {
                object obj = ResourceManager.GetObject("_88", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _89
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _89 {
            get {
                object obj = ResourceManager.GetObject("_89", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _9
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9 {
            get {
                object obj = ResourceManager.GetObject("_9", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _90
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _90 {
            get {
                object obj = ResourceManager.GetObject("_90", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _91
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _91 {
            get {
                object obj = ResourceManager.GetObject("_91", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _92
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _92 {
            get {
                object obj = ResourceManager.GetObject("_92", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _93
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _93 {
            get {
                object obj = ResourceManager.GetObject("_93", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _94
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _94 {
            get {
                object obj = ResourceManager.GetObject("_94", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _95
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _95 {
            get {
                object obj = ResourceManager.GetObject("_95", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _96
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _96 {
            get {
                object obj = ResourceManager.GetObject("_96", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _97
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _97 {
            get {
                object obj = ResourceManager.GetObject("_97", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _98
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _98 {
            get {
                object obj = ResourceManager.GetObject("_98", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the _99
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _99 {
            get {
                object obj = ResourceManager.GetObject("_99", resourceCulture);
                return ( (System.Drawing.Bitmap)( obj ) );
            }
        }

        /// <summary>
        /// Gets the database
        /// Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///	&lt;country name=&quot;Afghanistan&quot; file=&quot;_0&quot; /&gt;
        ///	&lt;country name=&quot;Albanië&quot; file=&quot;_1&quot; /&gt;
        ///	&lt;country name=&quot;Algerije&quot; file=&quot;_2&quot; /&gt;
        ///	&lt;country name=&quot;Andorra&quot; file=&quot;_3&quot; /&gt;
        ///	&lt;country name=&quot;Angola&quot; file=&quot;_4&quot; /&gt;
        ///	&lt;country name=&quot;Antigua en Barbuda&quot; file=&quot;_5&quot; /&gt;
        ///	&lt;country name=&quot;Argentinië&quot; file=&quot;_6&quot; /&gt;
        ///	&lt;country name=&quot;Armenië&quot; file=&quot;_7&quot; /&gt;
        ///	&lt;country name=&quot;Australië&quot; file=&quot;_8&quot; /&gt;
        ///	&lt;country name=&quot;Azerbeidzjan&quot; file=&quot;_9&quot; /&gt;
        ///	&lt;country name=&quot;Bahama&apos;s&quot; file=&quot;_10&quot; /&gt;
        ///	&lt;count [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string database {
            get {
                return ResourceManager.GetString( "database", resourceCulture );
            }
        }
    }
}
